title: Victor Luiz Almeida # your name (or website title) here
logo: "/images/foto circle.png?raw=true " # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm currently a Data Scientist at Itaú Unibanco 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/victor-luiz-almeida/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
